---
# tasks file for warserver
- name: install war packages
  apt: name={{ item }} state=installed
  with_items:
   - maven
   - git

- name: Clone repo
  git:
    repo: "{{ repo_link }}"
    dest: "{{ dest_path }}"

- name: maven package
  shell: mvn package
  args:
    chdir: /home/lab1
